name: 'Build and Test Hub'

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17.1
      - run: |
          sudo apt update && \
          sudo apt upgrade && \
          sudo apt-get install autoconf automake libtool curl make g++ unzip && \
          cd /tmp && \
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.1/protobuf-all-3.17.1.tar.gz && \
          tar xfzv protobuf-all-3.17.1.tar.gz && \
          cd protobuf-3.17.1 && \
          ./autogen.sh && \
          ./configure && \
          make && \
          sudo make install && \
          sudo ldconfig && \
          cd
      - run: pip install grpcio grpcio-tools github3.py
      - run: go get github.com/golang/protobuf/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - run: go build .
      - run: ./protobuf/build.sh
      - run: go test -v -race ./...
